Db challenge2
ytateno/quelcode-db pull request #2
Opened 2020-12-11 15:02 UTC by ytateno

2020-12-11 15:27 UTC, piasoratech requested changes
コメントしたので確認をお願いします
全体的に見直ししてみましょう

2020-12-11 15:27 UTC, piasoratech commented on db/db-challenge2/DDL.sql
> +CREATE TABLE user (
テーブルの命名は複数形が基本です

2020-12-11 15:27 UTC, piasoratech commented on db/db-challenge2/DDL.sql
> +    user_bio VARCHAR(1000),
そのテーブルの項目に当たるものはテーブル名をつけなくて大丈夫です
外部キーなどに当たる項目はテーブル名もつけるようにしましょう
intの場合も長さは指定して下さい

2020-12-11 15:27 UTC, piasoratech commented on db/db-challenge2/DDL.sql
> +    is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
MySQLでは真偽値はtinyint(1)で表すのが基本です

2020-12-11 15:27 UTC, piasoratech commented on db/db-challenge2/DDL.sql
> +    updated_date DATETIME NOT NULL
日時が入るカラムはもう少しいい命名があるので調べてみましょう

2020-12-11 15:27 UTC, piasoratech commented on db/db-challenge2/DDL.sql
> +    direct_chat_flag BOOLEAN DEFAULT FALSE NOT NULL,
フラグ系のカラムはもう少しいい命名があるので調べてみましょう

2020-12-11 15:27 UTC, piasoratech commented on db/db-challenge2/DDL.sql
> +    updated_user_id INT NOT NULL REFERENCES user(user_id),
作成者、更新者に当たるカラムももう少しいい命名があるので調べてみましょう
あとここはcreateの方ですかね？

2020-12-11 15:27 UTC, piasoratech commented on db/db-challenge2/DDL.sql
> +);
；の後に改行を入れておいてください

2020-12-11 23:26 UTC, ytateno commented on db/db-challenge2/DDL.sql
> +CREATE TABLE user (
複数形に変更しました。

2020-12-11 23:28 UTC, ytateno commented on db/db-challenge2/DDL.sql
> +    is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
BOOLEAMをTINYINT(1)に変更。それに伴って変更が必要な箇所に修正を加えました
。

2020-12-11 23:29 UTC, ytateno commented on db/db-challenge2/DDL.sql
> +    updated_date DATETIME NOT NULL
xxx_atに変更しました。

2020-12-11 23:30 UTC, ytateno commented on db/db-challenge2/DDL.sql
> +    direct_chat_flag BOOLEAN DEFAULT FALSE NOT NULL,
file_send_flag -> is_sent_file
direct_chat_flag-> is _direct_chat
に変更しました

2020-12-11 23:38 UTC, ytateno commented on db/db-challenge2/DDL.sql
> +    updated_user_id INT NOT NULL REFERENCES user(user_id),
全体を通してXXX_byに変更しました。
>あとここはcreateの方ですかね？
すみません寝ぼけていました。

2020-12-11 23:38 UTC, ytateno commented on db/db-challenge2/DDL.sql
> +);
;の後に改行を加えました。

2020-12-11 23:39 UTC, ytateno commented on db/db-challenge2/DDL.sql
> +    user_bio VARCHAR(1000),
カラム名を修正しました。
INTをすべてINT(11)に変更しました。
参考：http://piyopiyocs.blog115.fc2.com/blog-entry-1079.html

2020-12-12 03:19 UTC, choimake reviewed
拝見しました。
DDLは大丈夫だと思いますが。Excelシートの方で気になる点があったのでコメントしてます。
確認と対応お願いします。

- chatroomsのチャット概要のカラムがtypoしてます
- 定義書を修正した場合には、改訂履歴にもその旨を記載するようにしましょう

2020-12-15 11:22 UTC, ya-tateno commented
Excelのtypoを修正し、改訂履歴にも追記しました。
（改訂履歴ってこちら側が使うものだったんですね。。ここにきて気づく）

2020-12-15 13:28 UTC, choimake reviewed
拝見しました。以下の点について対応お願いします。

- 改訂履歴のテーブル名にtypoがあるので修正してください。

2020-12-15 13:33 UTC, ya-tateno commented
修正しました。確認お願いします。

2020-12-15 13:37 UTC, choimake approved these changes
対応ありがとうございました。LGTMです。

2021-01-12 13:28 UTC, merged